{{- if .Values.standaloneDnsProxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: standalone-dns-proxy-config
  namespace: {{ include "cilium.namespace" . }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.standaloneDnsProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    enable-l7-proxy: "false"
    debug: "false"
    enable-ipv4: "true"
    tofqdns-proxy-port: "40046"
    tofqdns-server-port: "40045"
    tofqdns-enable-dns-compression: "true"
{{- end }}
