{{- if .Values.standaloneDnsProxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: standalone-dns-proxy-config
  namespace: {{ include "cilium.namespace" . }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.standaloneDnsProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    enable-l7-proxy: {{ .Values.standaloneDnsProxy.l7Proxy.enabled | quote }}
    debug: {{ .Values.standaloneDnsProxy.debug.enabled | quote }}
    enable-ipv4: "true"
    tofqdns-proxy-port: {{ .Values.standaloneDnsProxy.proxyPort | quote }}
    tofqdns-server-port: {{ .Values.standaloneDnsProxy.serverPort | quote }}
    tofqdns-enable-dns-compression: {{ .Values.standaloneDnsProxy.enableDnsCompression | quote }}
{{- end }}
