{{- if .Values.standaloneDnsProxy.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: standalone-dns-proxy
  namespace: {{ include "cilium.namespace" . }}
  {{- with .Values.standaloneDnsProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    k8s-app: standalone-dns-proxy
    app.kubernetes.io/part-of: cilium
    app.kubernetes.io/name: standalone-dns-proxy
    name: standalone-dns-proxy
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  minReadySeconds: 5
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: standalone-dns-proxy
  # {{- with .Values.standaloneDnsProxy.updateStrategy }}
  # updateStrategy:
  #   {{- toYaml . | trim | nindent 4 }}
  # {{- end }}
  template:
    metadata:
      annotations:
        # {{- if and (.Values.envoy.rollOutPods) (not .Values.envoy.bootstrapConfigMap) }}
        # ensure pods roll when configmap updates
        cilium.io/standalone-dns-proxy-configmap-checksum: {{ include (print $.Template.BasePath "/standalone-dns-proxy/configmap.yaml") . | sha256sum | quote }}
        # {{- end }}
        # Set app AppArmor's profile to "unconfined". The value of this annotation
        # can be modified as long users know which profiles they have available
        # in AppArmor.
        container.apparmor.security.beta.kubernetes.io/standalone-dns-proxy: "unconfined"
      labels:
        k8s-app: standalone-dns-proxy
        name: standalone-dns-proxy
        app.kubernetes.io/name: standalone-dns-proxy
        app.kubernetes.io/part-of: cilium
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: true
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/os: linux
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: kubernetes.io/os
      #               operator: In
      #               values:
      #                 - linux
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: "Exists"
          effect: NoExecute
        - operator: "Exists"
          effect: NoSchedule
      containers:
        - name: standalone-dns-proxy
          image: {{ .Values.standaloneDnsProxy.image | quote }}
          args:
          - --config-dir=/tmp/standalone-dns-proxy/config-map
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              host: "127.0.0.1"
              port: 40046
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              host: "127.0.0.1"
              port: 40046
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /tmp/standalone-dns-proxy/config-map
            name: standalone-dns-proxy-config-path
            readOnly: true
          - mountPath: /var/run/cilium
            name: cilium-run
          - name: bpf-maps
            mountPath: /sys/fs/bpf
          securityContext:
            capabilities:
              add: ["BPF", "NET_ADMIN", "NET_RAW"]
              drop: ["ALL"]
      volumes:
      - name: cilium-run
        hostPath:
          path: /var/run/cilium
      - name: bpf-maps
        hostPath:
          path: /sys/fs/bpf
      - configMap:
          defaultMode: 420
          name: standalone-dns-proxy-config
        name: standalone-dns-proxy-config-path
{{- end }}
