// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: standalone-dns-proxy/standalone-dns-proxy.proto

package standalonednsproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FQDNData_SubscribeToDNSPolicies_FullMethodName = "/standalonednsproxy.FQDNData/SubscribeToDNSPolicies"
	FQDNData_UpdatesMappings_FullMethodName        = "/standalonednsproxy.FQDNData/UpdatesMappings"
)

// FQDNDataClient is the client API for FQDNData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FQDNDataClient interface {
	SubscribeToDNSPolicies(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DNSPoliciesResult, DNSPolicies], error)
	UpdatesMappings(ctx context.Context, in *FQDNMapping, opts ...grpc.CallOption) (*UpdatesMappingsResult, error)
}

type fQDNDataClient struct {
	cc grpc.ClientConnInterface
}

func NewFQDNDataClient(cc grpc.ClientConnInterface) FQDNDataClient {
	return &fQDNDataClient{cc}
}

func (c *fQDNDataClient) SubscribeToDNSPolicies(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DNSPoliciesResult, DNSPolicies], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FQDNData_ServiceDesc.Streams[0], FQDNData_SubscribeToDNSPolicies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DNSPoliciesResult, DNSPolicies]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNData_SubscribeToDNSPoliciesClient = grpc.BidiStreamingClient[DNSPoliciesResult, DNSPolicies]

func (c *fQDNDataClient) UpdatesMappings(ctx context.Context, in *FQDNMapping, opts ...grpc.CallOption) (*UpdatesMappingsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatesMappingsResult)
	err := c.cc.Invoke(ctx, FQDNData_UpdatesMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FQDNDataServer is the server API for FQDNData service.
// All implementations should embed UnimplementedFQDNDataServer
// for forward compatibility.
type FQDNDataServer interface {
	SubscribeToDNSPolicies(grpc.BidiStreamingServer[DNSPoliciesResult, DNSPolicies]) error
	UpdatesMappings(context.Context, *FQDNMapping) (*UpdatesMappingsResult, error)
}

// UnimplementedFQDNDataServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFQDNDataServer struct{}

func (UnimplementedFQDNDataServer) SubscribeToDNSPolicies(grpc.BidiStreamingServer[DNSPoliciesResult, DNSPolicies]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToDNSPolicies not implemented")
}
func (UnimplementedFQDNDataServer) UpdatesMappings(context.Context, *FQDNMapping) (*UpdatesMappingsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatesMappings not implemented")
}
func (UnimplementedFQDNDataServer) testEmbeddedByValue() {}

// UnsafeFQDNDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FQDNDataServer will
// result in compilation errors.
type UnsafeFQDNDataServer interface {
	mustEmbedUnimplementedFQDNDataServer()
}

func RegisterFQDNDataServer(s grpc.ServiceRegistrar, srv FQDNDataServer) {
	// If the following call pancis, it indicates UnimplementedFQDNDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FQDNData_ServiceDesc, srv)
}

func _FQDNData_SubscribeToDNSPolicies_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FQDNDataServer).SubscribeToDNSPolicies(&grpc.GenericServerStream[DNSPoliciesResult, DNSPolicies]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNData_SubscribeToDNSPoliciesServer = grpc.BidiStreamingServer[DNSPoliciesResult, DNSPolicies]

func _FQDNData_UpdatesMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FQDNMapping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNDataServer).UpdatesMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNData_UpdatesMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNDataServer).UpdatesMappings(ctx, req.(*FQDNMapping))
	}
	return interceptor(ctx, in, info, handler)
}

// FQDNData_ServiceDesc is the grpc.ServiceDesc for FQDNData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FQDNData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "standalonednsproxy.FQDNData",
	HandlerType: (*FQDNDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatesMappings",
			Handler:    _FQDNData_UpdatesMappings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToDNSPolicies",
			Handler:       _FQDNData_SubscribeToDNSPolicies_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "standalone-dns-proxy/standalone-dns-proxy.proto",
}
