apiVersion: v1
data:
  oai.server: |
    internal.api.openai.org:53 {
        errors
        template IN A {
            answer "{{ .Name }} 60 IN A 10.10.0.4"
        }
        template IN AAAA {
            authority "internal.api.openai.org. 60 IN SOA ns.internal.api.openai.org. h.internal.api.openai.org. 1 7200 900 1209600 60"
        }
    }
  partner.server: |
    partner.example.test:53 {
        errors
        template IN A {
            answer "{{ .Name }} 60 IN A 10.10.0.4"
        }
        template IN AAAA {
            authority "partner.example.test. 60 IN SOA ns.partner.example.test. h.partner.example.test. 1 7200 900 1209600 60"
        }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"oai.server":"internal.api.openai.org:53 {\n    errors\n    template IN A {\n        answer \"{{ .Name }} 60 IN A 10.10.0.4\"\n    }\n    template IN AAAA {\n        authority \"internal.api.openai.org. 60 IN SOA ns.internal.api.openai.org. h.internal.api.openai.org. 1 7200 900 1209600 60\"\n    }\n}\n","partner.server":"partner.example.test:53 {\n    errors\n    template IN A {\n        answer \"{{ .Name }} 60 IN A 10.10.0.4\"\n    }\n    template IN AAAA {\n        authority \"partner.example.test. 60 IN SOA ns.partner.example.test. h.partner.example.test. 1 7200 900 1209600 60\"\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"coredns-custom","namespace":"kube-system"}}
  creationTimestamp: "2026-09-03T17:42:23Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
  name: coredns-custom
  namespace: kube-system
  resourceVersion: "437381"
  uid: dd871baf-fed0-4fa3-a7f9-8b169ea52fef
