// Code generated by go-swagger; DO NOT EDIT.
// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

// Package server Standalone DNS Proxy
//
//	API for Standalone DNS Proxy
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: v1beta
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//	  - text/plain
//
// swagger:meta
package server
