// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for Standalone DNS Proxy",
    "title": "Standalone DNS Proxy",
    "version": "v1beta"
  },
  "basePath": "/v1",
  "paths": {
    "/healthz": {
      "get": {
        "description": "Returns the status of Standalone DNS Proxy instance.",
        "produces": [
          "text/plain"
        ],
        "tags": [
          "sdp"
        ],
        "summary": "Get health of Standalone DNS Proxy",
        "responses": {
          "200": {
            "description": "Standalone DNS Proxy is healthy",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Standalone DNS Proxy is not healthy",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "x-schemes": [
    "unix"
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for Standalone DNS Proxy",
    "title": "Standalone DNS Proxy",
    "version": "v1beta"
  },
  "basePath": "/v1",
  "paths": {
    "/healthz": {
      "get": {
        "description": "Returns the status of Standalone DNS Proxy instance.",
        "produces": [
          "text/plain"
        ],
        "tags": [
          "sdp"
        ],
        "summary": "Get health of Standalone DNS Proxy",
        "responses": {
          "200": {
            "description": "Standalone DNS Proxy is healthy",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Standalone DNS Proxy is not healthy",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "x-schemes": [
    "unix"
  ]
}`))
}
