apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: client-egress-standalone-dns-proxy
spec:
  endpointSelector:
    matchLabels:
      kind: client
  egress:
  - toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
      rules:
        dns:
        - matchPattern: "one.one.one.one"
    toEndpoints:
      - matchExpressions:
          - { key: 'k8s-app', operator: In, values: [ "kube-dns", "coredns", "node-local-dns", "nodelocaldns" ] }
          - { key: 'io.kubernetes.pod.namespace', operator: In, values: [ "kube-system" ] }
          - { key: 'io.cilium.k8s.policy.cluster', operator: In, values: [ "{{.ClusterName}}" ] }